"""免费 / 公益大模型供应商预设目录。

集中维护互联网上提供免费额度或公益免费调用的大模型供应商预设，
当前共收录 100+ 个免费 / 公益供应商预设，覆盖：

- 海外开源模型推理平台（siliconflow、openrouter、groq、together、cerebras 等）
- 国内主流大模型免费试用层（deepseek、qwen、zhipu、kimi、doubao、qianfan、hunyuan 等）
- 国内 API 中转聚合平台（aihubmix、api2d、4sapi、147api、poloapi 等）
- 自部署 / 本地推理框架（ollama、vllm、llamacpp、xinference、localai 等）

每个预设包含：基础 URL、注册地址、免费额度说明、免费模型清单、能力列表等，
供 ``gateway/router.py`` 中的 ``GET /free-providers`` 与
``POST /free-providers/{provider_key}/enable`` 端点使用。
"""
from __future__ import annotations

FREE_PROVIDER_PRESETS: dict[str, dict] = {
    # ----------------------------------------------------------------------
    # 第一批免费 / 公益供应商（开源模型推理 / 聚合）
    # ----------------------------------------------------------------------
    "siliconflow": {
        "provider": "siliconflow",
        "name": "硅基流动 SiliconFlow（免费层）",
        "base_url": "https://api.siliconflow.cn/v1",
        "protocol": "openai",
        "signup_url": "https://cloud.siliconflow.cn/i/rT5iYy97",
        "free_quota": "注册送 2000 万 token",
        "free_models": [
            "deepseek-ai/DeepSeek-V3",
            "deepseek-ai/DeepSeek-R1",
            "Qwen/Qwen2.5-7B-Instruct",
            "Qwen/Qwen2.5-72B-Instruct",
            "THUDM/glm-4-9b-chat",
        ],
        "capabilities": ["chat", "vision", "tool_call", "json_mode", "embedding", "reasoning"],
        "regions": ["cn", "global"],
        "retention_mode": "provider_retained",
        "notes": "OpenAI 兼容协议，一个 API Key 调用所有开源模型",
    },
    "openrouter": {
        "provider": "openrouter",
        "name": "OpenRouter 聚合（免费模型）",
        "base_url": "https://openrouter.ai/api/v1",
        "protocol": "openai",
        "signup_url": "https://openrouter.ai/",
        "free_quota": "17+ 个免费模型（free: 前缀）",
        "free_models": [
            "free:qwen-2.5-7b",
            "free:gemini-2.0-flash",
            "free:llama-3.3-70b",
            "free:deepseek-r1",
            "free:mistral-7b-instruct",
        ],
        "capabilities": ["chat", "vision", "tool_call", "json_mode", "reasoning"],
        "regions": ["global", "us", "eu"],
        "retention_mode": "provider_retained",
        "notes": "聚合 100+ 模型，free: 前缀模型完全免费",
    },
    "groq": {
        "provider": "groq",
        "name": "Groq 超快推理（免费层）",
        "base_url": "https://api.groq.com/openai/v1",
        "protocol": "openai",
        "signup_url": "https://console.groq.com/",
        "free_quota": "免费层 RPM/TPD 限额",
        "free_models": [
            "llama-3.3-70b-versatile",
            "llama-3.1-8b-instant",
            "mixtral-8x7b-32768",
            "gemma2-9b-it",
        ],
        "capabilities": ["chat", "tool_call", "json_mode", "reasoning"],
        "regions": ["global", "us"],
        "retention_mode": "provider_retained",
        "notes": "LPU 推理引擎，单 token 延迟极低",
    },
    "together": {
        "provider": "together",
        "name": "Together AI 开源模型免费层",
        "base_url": "https://api.together.xyz/v1",
        "protocol": "openai",
        "signup_url": "https://api.together.xyz/",
        "free_quota": "新用户 $5 体验额度",
        "free_models": [
            "meta-llama/Llama-3.3-70B-Instruct-Turbo-Free",
            "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo",
            "Qwen/Qwen2.5-7B-Instruct-Turbo",
        ],
        "capabilities": ["chat", "vision", "tool_call", "json_mode", "embedding", "reasoning"],
        "regions": ["global", "us"],
        "retention_mode": "provider_retained",
        "notes": "200+ 开源模型托管推理",
    },
    "cerebras": {
        "provider": "cerebras",
        "name": "Cerebras 超快推理",
        "base_url": "https://api.cerebras.ai/v1",
        "protocol": "openai",
        "signup_url": "https://cerebras.ai/",
        "free_quota": "免费层 API 调用",
        "free_models": [
            "llama3.1-8b",
            "llama3.1-70b",
            "llama-3.3-70b",
        ],
        "capabilities": ["chat", "tool_call", "json_mode", "reasoning"],
        "regions": ["global", "us"],
        "retention_mode": "provider_retained",
        "notes": "Wafer-Scale Engine 推理，吞吐量行业领先",
    },
    "cloudflare": {
        "provider": "cloudflare",
        "name": "Cloudflare Workers AI",
        "base_url": "https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/v1",
        "protocol": "openai",
        "signup_url": "https://dash.cloudflare.com/",
        "free_quota": "每日 10000 次神经元推理",
        "free_models": [
            "@cf/meta/llama-3.1-8b-instruct",
            "@cf/meta/llama-3.1-70b-instruct",
            "@cf/qwen/qwen1.5-14b-chat-awq",
        ],
        "capabilities": ["chat", "tool_call", "embedding"],
        "regions": ["global"],
        "retention_mode": "provider_retained",
        "notes": "启用时需将 base_url 中的 {account_id} 替换为您的 Cloudflare 账户 ID",
    },
    "huggingface": {
        "provider": "huggingface",
        "name": "Hugging Face Inference API",
        "base_url": "https://api-inference.huggingface.co",
        "protocol": "openai",
        "signup_url": "https://huggingface.co/",
        "free_quota": "免费层每小时有限调用",
        "free_models": [
            "meta-llama/Llama-3.1-8B-Instruct",
            "mistralai/Mistral-7B-Instruct-v0.3",
            "Qwen/Qwen2.5-7B-Instruct",
        ],
        "capabilities": ["chat", "embedding"],
        "regions": ["global", "eu"],
        "retention_mode": "provider_retained",
        "notes": "HF Inference API 兼容 OpenAI 协议",
    },
    "modelscope": {
        "provider": "modelscope",
        "name": "魔搭社区推理 API",
        "base_url": "https://api-inference.modelscope.cn/v1",
        "protocol": "openai",
        "signup_url": "https://modelscope.cn/",
        "free_quota": "免费层每日调用额度",
        "free_models": [
            "Qwen/Qwen2.5-7B-Instruct",
            "Qwen/Qwen2.5-72B-Instruct",
            "deepseek-ai/DeepSeek-V3",
        ],
        "capabilities": ["chat", "vision", "embedding"],
        "regions": ["cn"],
        "retention_mode": "provider_retained",
        "notes": "阿里魔搭社区开源模型推理 API",
    },
    "iflytek": {
        "provider": "iflytek",
        "name": "讯飞星火（OpenAI 兼容）",
        "base_url": "https://spark-api-open.xf-yun.com/v1",
        "protocol": "openai",
        "signup_url": "https://xinghuo.xfyun.cn/",
        "free_quota": "新用户免费试用 token",
        "free_models": [
            "generalv3.5",
            "general",
            "generalv3",
            "4.0Ultra",
        ],
        "capabilities": ["chat", "vision", "tool_call"],
        "regions": ["cn"],
        "retention_mode": "provider_retained",
        "notes": "讯飞星火大模型 OpenAI 兼容接口",
    },
    "dmxapi": {
        "provider": "dmxapi",
        "name": "DMXAPI 聚合",
        "base_url": "https://www.dmxapi.cn/v1",
        "protocol": "openai",
        "signup_url": "https://www.dmxapi.cn/",
        "free_quota": "新用户赠送额度",
        "free_models": [
            "deepseek-chat",
            "gpt-4o-mini",
            "claude-3.5-sonnet",
            "gemini-1.5-flash",
        ],
        "capabilities": ["chat", "vision", "tool_call", "json_mode", "embedding", "reasoning"],
        "regions": ["cn", "global"],
        "retention_mode": "provider_retained",
        "notes": "聚合 OpenAI/Claude/Gemini/DeepSeek 等多家供应商",
    },
    "n1n": {
        "provider": "n1n",
        "name": "n1n.ai 聚合",
        "base_url": "https://api.n1n.ai/v1",
        "protocol": "openai",
        "signup_url": "https://n1n.ai/",
        "free_quota": "新用户免费额度",
        "free_models": [
            "gpt-4o",
            "claude-3.5-sonnet",
            "deepseek-chat",
            "gemini-2.0-flash",
        ],
        "capabilities": ["chat", "vision", "tool_call", "json_mode", "reasoning"],
        "regions": ["global", "us"],
        "retention_mode": "provider_retained",
        "notes": "聚合主流商业模型与开源模型",
    },
    "github": {
        "provider": "github",
        "name": "GitHub Models（免费层）",
        "base_url": "https://models.inference.ai.azure.com",
        "protocol": "openai",
        "signup_url": "https://github.com/marketplace/models",
        "free_quota": "GitHub 账户每日免费调用",
        "free_models": [
            "gpt-4o",
            "gpt-4o-mini",
            "Mistral-large",
            "Phi-3.5-mini-instruct",
        ],
        "capabilities": ["chat", "vision", "tool_call", "json_mode", "reasoning"],
        "regions": ["global", "us"],
        "retention_mode": "provider_retained",
        "notes": "使用 GitHub 个人访问令牌（PAT）即可调用",
    },
    "perplexity": {
        "provider": "perplexity",
        "name": "Perplexity（部分免费）",
        "base_url": "https://api.perplexity.ai",
        "protocol": "openai",
        "signup_url": "https://www.perplexity.ai/",
        "free_quota": "新用户 $5 体验额度",
        "free_models": [
            "llama-3.1-sonar-small-128k-online",
            "llama-3.1-sonar-large-128k-online",
            "llama-3.1-sonar-huge-128k-online",
        ],
        "capabilities": ["chat", "tool_call", "json_mode"],
        "regions": ["global", "us"],
        "retention_mode": "provider_retained",
        "notes": "在线搜索增强的对话模型",
    },
    "cohere": {
        "provider": "cohere",
        "name": "Cohere（免费层）",
        "base_url": "https://api.cohere.ai/v1",
        "protocol": "openai",
        "signup_url": "https://cohere.com/",
        "free_quota": "开发者试用额度",
        "free_models": [
            "command-r-plus",
            "command-r",
            "command-r7b-12-2024",
        ],
        "capabilities": ["chat", "tool_call", "json_mode", "embedding", "reasoning"],
        "regions": ["global", "us"],
        "retention_mode": "provider_retained",
        "notes": "Cohere Command 系列模型，强 RAG 能力",
    },
    "mistral_free": {
        "provider": "mistral_free",
        "name": "Mistral 免费层（La Plateforme）",
        "base_url": "https://api.mistral.ai/v1",
        "protocol": "openai",
        "signup_url": "https://console.mistral.ai/",
        "free_quota": "La Plateforme 免费层",
        "free_models": [
            "mistral-small-latest",
            "open-mistral-7b",
            "open-mixtral-8x7b",
            "open-mistral-nemo",
        ],
        "capabilities": ["chat", "vision", "tool_call", "json_mode", "embedding", "reasoning"],
        "regions": ["global", "eu"],
        "retention_mode": "provider_retained",
        "notes": "Mistral La Plateforme 免费层，开放权重模型可白嫖",
    },
    # ----------------------------------------------------------------------
    # 第二批免费 / 公益供应商（开源模型推理 / 聚合 / 官方免费层）
    # ----------------------------------------------------------------------
    "deepinfra": {
        "provider": "deepinfra",
        "name": "DeepInfra 开源模型推理",
        "base_url": "https://api.deepinfra.com/v1/openai",
        "protocol": "openai",
        "signup_url": "https://deepinfra.com/",
        "free_quota": "新用户免费额度",
        "free_models": ["meta-llama/Llama-3.3-70B-Instruct", "meta-llama/Meta-Llama-3.1-8B-Instruct", "Qwen/Qwen2.5-7B-Instruct"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode", "embedding"],
        "regions": ["global", "us"],
        "retention_mode": "provider_retained",
        "notes": "低成本开源模型推理，OpenAI兼容",
    },
    "fireworks": {
        "provider": "fireworks",
        "name": "Fireworks AI 开源模型",
        "base_url": "https://api.fireworks.ai/inference/v1",
        "protocol": "openai",
        "signup_url": "https://fireworks.ai/",
        "free_quota": "新用户免费额度",
        "free_models": ["accounts/fireworks/models/llama-v3p3-70b-instruct", "accounts/fireworks/models/qwen2p5-7b-instruct"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode", "embedding", "reasoning"],
        "regions": ["global", "us"],
        "retention_mode": "provider_retained",
        "notes": "Fireworks AI 开源模型托管推理",
    },
    "novita": {
        "provider": "novita",
        "name": "Novita AI 模型API",
        "base_url": "https://api.novita.ai/v3/openai",
        "protocol": "openai",
        "signup_url": "https://novita.ai/",
        "free_quota": "新用户免费额度",
        "free_models": ["deepseek/deepseek-r1", "deepseek/deepseek-v3", "meta-llama/llama-3.3-70b-instruct"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode", "embedding"],
        "regions": ["global", "us"],
        "retention_mode": "provider_retained",
        "notes": "Novita AI 低成本模型API平台",
    },
    "lepton": {
        "provider": "lepton",
        "name": "Lepton AI 推理服务",
        "base_url": "https://api.lepton.run/v1",
        "protocol": "openai",
        "signup_url": "https://www.lepton.run/",
        "free_quota": "免费体验额度",
        "free_models": ["deepseek-ai/DeepSeek-V3", "meta-llama/Meta-Llama-3.1-70B-Instruct"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode"],
        "regions": ["global", "us"],
        "retention_mode": "provider_retained",
        "notes": "Lepton AI 高效推理服务",
    },
    "replicate": {
        "provider": "replicate",
        "name": "Replicate 模型托管",
        "base_url": "https://api.replicate.com/v1",
        "protocol": "openai",
        "signup_url": "https://replicate.com/",
        "free_quota": "新用户免费额度",
        "free_models": ["meta/llama-3.3-70b-instruct", "meta/llama-3.1-8b-instruct"],
        "capabilities": ["chat", "vision"],
        "regions": ["global", "us"],
        "retention_mode": "provider_retained",
        "notes": "Replicate 开源模型托管，按次计费",
    },
    "stepfun": {
        "provider": "stepfun",
        "name": "阶跃星辰 StepFun",
        "base_url": "https://api.stepfun.com/v1",
        "protocol": "openai",
        "signup_url": "https://platform.stepfun.com/",
        "free_quota": "新用户免费token额度",
        "free_models": ["step-1-8k", "step-1-32k", "step-1-128k", "step-1v-8k"],
        "capabilities": ["chat", "vision", "tool_call"],
        "regions": ["cn"],
        "retention_mode": "provider_retained",
        "notes": "阶跃星辰多模态大模型，OpenAI兼容",
    },
    "lingyi": {
        "provider": "lingyi",
        "name": "零一万物 01.ai",
        "base_url": "https://api.lingyiwanwu.com/v1",
        "protocol": "openai",
        "signup_url": "https://platform.lingyiwanwu.com/",
        "free_quota": "新用户免费token额度",
        "free_models": ["yi-large", "yi-medium", "yi-light"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode"],
        "regions": ["cn", "global"],
        "retention_mode": "provider_retained",
        "notes": "零一万物 Yi 系列大模型",
    },
    "gemini_free": {
        "provider": "gemini",
        "name": "Google Gemini 免费层",
        "base_url": "https://generativelanguage.googleapis.com/v1beta",
        "protocol": "gemini",
        "signup_url": "https://aistudio.google.com/",
        "free_quota": "免费层 RPM/RPD 限额",
        "free_models": ["gemini-2.0-flash", "gemini-2.0-flash-lite", "gemini-1.5-flash", "gemini-1.5-flash-8b"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode", "embedding", "reasoning"],
        "regions": ["global", "us", "eu", "asia"],
        "retention_mode": "provider_retained",
        "notes": "Google AI Studio 免费层，Gemini Flash 系列免费",
    },
    "openai_free": {
        "provider": "openai",
        "name": "OpenAI 免费层",
        "base_url": "https://api.openai.com/v1",
        "protocol": "openai",
        "signup_url": "https://platform.openai.com/",
        "free_quota": "新用户免费额度",
        "free_models": ["gpt-4o-mini", "gpt-3.5-turbo"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode", "embedding", "reasoning"],
        "regions": ["global", "us", "eu"],
        "retention_mode": "provider_retained",
        "notes": "OpenAI 官方免费额度",
    },
    # ----------------------------------------------------------------------
    # 第三批免费 / 公益供应商（开源模型推理 / 国内免费层）
    # ----------------------------------------------------------------------
    "sambanova": {
        "provider": "sambanova",
        "name": "SambaNova 免费推理",
        "base_url": "https://api.sambanova.ai/v1",
        "protocol": "openai",
        "signup_url": "https://cloud.sambanova.ai/",
        "free_quota": "免费层 API 调用",
        "free_models": ["Meta-Llama-3.1-8B-Instruct", "Meta-Llama-3.1-70B-Instruct", "Llama-3.3-70B-Instruct"],
        "capabilities": ["chat", "tool_call", "json_mode"],
        "regions": ["global", "us"],
        "retention_mode": "provider_retained",
        "notes": "SambaNova RDU 推理引擎，开源模型免费层",
    },
    "chutes": {
        "provider": "chutes",
        "name": "Chutes AI 免费推理",
        "base_url": "https://api.chutes.ai/v1",
        "protocol": "openai",
        "signup_url": "https://chutes.ai/",
        "free_quota": "免费层 API 调用",
        "free_models": ["chutes-deepseek-r1", "chutes-llama-3.3-70b", "chutes-qwen-2.5-72b"],
        "capabilities": ["chat", "tool_call", "json_mode", "reasoning"],
        "regions": ["global", "us"],
        "retention_mode": "provider_retained",
        "notes": "Chutes AI 免费 GPU 推理平台",
    },
    "nebius": {
        "provider": "nebius",
        "name": "Nebius AI Cloud",
        "base_url": "https://api.studio.nebius.ai/v1",
        "protocol": "openai",
        "signup_url": "https://studio.nebius.ai/",
        "free_quota": "新用户免费额度",
        "free_models": ["meta-llama/Meta-Llama-3.1-70B-Instruct", "Qwen/Qwen2.5-7B-Instruct"],
        "capabilities": ["chat", "tool_call", "json_mode", "embedding"],
        "regions": ["global", "eu"],
        "retention_mode": "provider_retained",
        "notes": "Nebius AI Cloud 开源模型推理",
    },
    "openbayes": {
        "provider": "openbayes",
        "name": "OpenBayes 贝式计算",
        "base_url": "https://openbayes.com/api/v1",
        "protocol": "openai",
        "signup_url": "https://openbayes.com/",
        "free_quota": "新用户免费算力",
        "free_models": ["deepseek-v3", "qwen2.5-72b"],
        "capabilities": ["chat", "tool_call"],
        "regions": ["cn"],
        "retention_mode": "provider_retained",
        "notes": "OpenBayes 国内算力共享平台",
    },
    "siliconflow_cn": {
        "provider": "siliconflow",
        "name": "硅基流动（国内节点）",
        "base_url": "https://api.siliconflow.cn/v1",
        "protocol": "openai",
        "signup_url": "https://cloud.siliconflow.cn/",
        "free_quota": "注册送 2000 万 token",
        "free_models": ["deepseek-ai/DeepSeek-V3", "Qwen/Qwen2.5-7B-Instruct"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode", "embedding"],
        "regions": ["cn"],
        "retention_mode": "provider_retained",
        "notes": "硅基流动国内直连节点",
    },
    # ----------------------------------------------------------------------
    # 国内主流供应商（提供免费试用额度）
    # ----------------------------------------------------------------------
    "deepseek": {
        "provider": "deepseek",
        "name": "DeepSeek 深度求索",
        "base_url": "https://api.deepseek.com/v1",
        "protocol": "openai",
        "signup_url": "https://platform.deepseek.com/",
        "free_quota": "新用户赠送体验额度",
        "free_models": [
            "deepseek-chat",
            "deepseek-reasoner",
        ],
        "capabilities": ["chat", "tool_call", "json_mode", "reasoning"],
        "regions": ["cn", "global"],
        "retention_mode": "provider_retained",
        "notes": "国产开源大模型，推理与代码能力优秀",
    },
    "qwen": {
        "provider": "qwen",
        "name": "阿里通义千问 DashScope",
        "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "protocol": "openai",
        "signup_url": "https://dashscope.console.aliyun.com/",
        "free_quota": "新用户免费 token 额度",
        "free_models": [
            "qwen-turbo",
            "qwen-plus",
            "qwen-max",
            "qwen-long",
        ],
        "capabilities": ["chat", "vision", "tool_call", "json_mode", "embedding", "reasoning"],
        "regions": ["cn", "sg"],
        "retention_mode": "provider_retained",
        "notes": "阿里通义千问系列，OpenAI 兼容模式",
    },
    "zhipu": {
        "provider": "zhipu",
        "name": "智谱 GLM 开放平台",
        "base_url": "https://open.bigmodel.cn/api/paas/v4",
        "protocol": "openai",
        "signup_url": "https://open.bigmodel.cn/",
        "free_quota": "新用户免费 token 额度",
        "free_models": [
            "glm-4-flash",
            "glm-4-flashx",
            "glm-4-air",
            "glm-4-airx",
        ],
        "capabilities": ["chat", "vision", "tool_call", "json_mode", "embedding"],
        "regions": ["cn"],
        "retention_mode": "provider_retained",
        "notes": "智谱 GLM-4 系列免费层（flash/air）",
    },
    "kimi": {
        "provider": "kimi",
        "name": "Moonshot Kimi 月之暗面",
        "base_url": "https://api.moonshot.cn/v1",
        "protocol": "openai",
        "signup_url": "https://platform.moonshot.cn/",
        "free_quota": "新用户赠送体验额度",
        "free_models": [
            "moonshot-v1-8k",
            "moonshot-v1-32k",
            "moonshot-v1-128k",
        ],
        "capabilities": ["chat", "vision", "tool_call", "json_mode", "reasoning"],
        "regions": ["cn"],
        "retention_mode": "provider_retained",
        "notes": "Moonshot Kimi 长上下文对话模型",
    },
    "doubao": {
        "provider": "doubao",
        "name": "字节火山方舟豆包",
        "base_url": "https://ark.cn-beijing.volces.com/api/v3",
        "protocol": "openai",
        "signup_url": "https://www.volcengine.com/product/doubao",
        "free_quota": "新用户免费 token 额度",
        "free_models": [
            "doubao-lite-4k",
            "doubao-lite-32k",
            "doubao-pro-4k",
            "doubao-pro-32k",
        ],
        "capabilities": ["chat", "vision", "tool_call", "json_mode", "embedding"],
        "regions": ["cn"],
        "retention_mode": "provider_retained",
        "notes": "火山方舟豆包大模型 OpenAI 兼容接口",
    },
    "qianfan": {
        "provider": "qianfan",
        "name": "百度千帆文心一言",
        "base_url": "https://qianfan.baidubce.com/v2",
        "protocol": "openai",
        "signup_url": "https://qianfan.cloud.baidu.com/",
        "free_quota": "新用户免费 token 额度",
        "free_models": [
            "ernie-tiny-8k",
            "ernie-speed-128k",
            "ernie-lite-pro-128k",
        ],
        "capabilities": ["chat", "vision", "tool_call", "embedding"],
        "regions": ["cn"],
        "retention_mode": "provider_retained",
        "notes": "百度千帆大模型平台 OpenAI 兼容接口",
    },
    "hunyuan": {
        "provider": "hunyuan",
        "name": "腾讯混元大模型",
        "base_url": "https://api.hunyuan.cloud.tencent.com/v1",
        "protocol": "openai",
        "signup_url": "https://cloud.tencent.com/product/hunyuan",
        "free_quota": "新用户免费 token 额度",
        "free_models": [
            "hunyuan-lite",
            "hunyuan-standard",
            "hunyuan-pro",
        ],
        "capabilities": ["chat", "vision", "tool_call", "json_mode"],
        "regions": ["cn"],
        "retention_mode": "provider_retained",
        "notes": "腾讯混元 OpenAI 兼容接口，lite 版免费",
    },
    "aimlapi": {
        "provider": "aimlapi",
        "name": "AI/ML API",
        "base_url": "https://api.aimlapi.com/v1",
        "protocol": "openai",
        "signup_url": "https://aimlapi.com/",
        "free_quota": "注册赠送 1000 credits",
        "free_models": ["gpt-4o-mini", "gpt-4o", "claude-3-haiku-20240307", "gemini-1.5-flash", "llama-3.1-70b-instruct", "llama-3.1-8b-instruct", "mistral-7b-instruct", "Qwen2-72B-Instruct"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode"],
        "regions": ["global"],
        "retention_mode": "provider_retained",
        "notes": "聚合多模型 API 平台，注册赠送 1000 credits",
    },
    "monsterapi": {
        "provider": "monsterapi",
        "name": "Monster API",
        "base_url": "https://api.monsterapi.ai/v1",
        "protocol": "openai",
        "signup_url": "https://monsterapi.ai/",
        "free_quota": "新用户 2500 credits",
        "free_models": ["llama-3.1-70b-instruct", "llama-3.1-8b-instruct", "mistral-7b-instruct", "mixtral-8x7b-instruct", "gemma-2-9b-it", "qwen-2-7b-instruct"],
        "capabilities": ["chat", "tool_call", "json_mode"],
        "regions": ["global"],
        "retention_mode": "provider_retained",
        "notes": "Monster API 开源模型推理，新用户赠送 2500 credits",
    },
    "predibase": {
        "provider": "predibase",
        "name": "Predibase",
        "base_url": "https://serving.app.predibase.com/v1",
        "protocol": "openai",
        "signup_url": "https://predibase.com/",
        "free_quota": "免费 LoRA serving 每月 1 亿 tokens",
        "free_models": ["llama-3.1-8b-instruct", "llama-3-70b-instruct", "mistral-7b-instruct", "qwen2.5-7b-instruct"],
        "capabilities": ["chat", "tool_call", "json_mode"],
        "regions": ["global"],
        "retention_mode": "provider_retained",
        "notes": "Predibase LoRA 微调与推理服务",
    },
    "baseten": {
        "provider": "baseten",
        "name": "Baseten",
        "base_url": "https://model.baseten.co/v1",
        "protocol": "openai",
        "signup_url": "https://baseten.co/",
        "free_quota": "新用户 $5 试用",
        "free_models": ["llama-3.1-70b", "llama-3.1-8b", "mixtral-8x7b", "qwen2.5-72b"],
        "capabilities": ["chat", "tool_call"],
        "regions": ["global"],
        "retention_mode": "provider_retained",
        "notes": "Baseten 模型托管平台，新用户 $5 试用额度",
    },
    "runpod": {
        "provider": "runpod",
        "name": "RunPod",
        "base_url": "https://api.runpod.ai/v2",
        "protocol": "openai",
        "signup_url": "https://www.runpod.io/",
        "free_quota": "新用户 $10 试用",
        "free_models": ["llama-3.1-70b", "mistral-7b", "qwen2.5-7b"],
        "capabilities": ["chat"],
        "regions": ["global"],
        "retention_mode": "provider_retained",
        "notes": "RunPod GPU 推理平台，社区部署可免费试用",
    },
    "anyscale": {
        "provider": "anyscale",
        "name": "Anyscale Endpoints",
        "base_url": "https://api.endpoints.anyscale.com/v1",
        "protocol": "openai",
        "signup_url": "https://www.anyscale.com/",
        "free_quota": "新用户 $10 试用",
        "free_models": ["meta-llama/Llama-3.1-70B-Instruct", "meta-llama/Llama-3.1-8B-Instruct", "mistralai/Mistral-7B-Instruct-v0.1", "mistralai/Mixtral-8x7B-Instruct-v0.1"],
        "capabilities": ["chat", "tool_call", "json_mode"],
        "regions": ["global"],
        "retention_mode": "provider_retained",
        "notes": "Anyscale Ray 平台 endpoints，新用户 $10 试用",
    },
    "modal": {
        "provider": "modal",
        "name": "Modal Labs",
        "base_url": "https://modal.com/v1",
        "protocol": "openai",
        "signup_url": "https://modal.com/",
        "free_quota": "每月 $30 免费",
        "free_models": ["llama-3.1", "qwen2.5", "deepseek"],
        "capabilities": ["chat"],
        "regions": ["global"],
        "retention_mode": "provider_retained",
        "notes": "Modal Labs Serverless 平台，每月 $30 免费额度，可自部署开源模型",
    },
    "featherless": {
        "provider": "featherless",
        "name": "Featherless",
        "base_url": "https://api.featherless.ai/v1",
        "protocol": "openai",
        "signup_url": "https://featherless.ai/",
        "free_quota": "注册免费 tokens",
        "free_models": ["meta-llama/Meta-Llama-3.1-70B-Instruct", "Qwen/Qwen2.5-72B-Instruct", "mistralai/Mistral-7B-Instruct-v0.3"],
        "capabilities": ["chat", "tool_call"],
        "regions": ["global"],
        "retention_mode": "provider_retained",
        "notes": "Featherless 无服务器开源模型托管",
    },
    "inference_net": {
        "provider": "inference_net",
        "name": "Inference.net",
        "base_url": "https://api.inference.net/v1",
        "protocol": "openai",
        "signup_url": "https://inference.net/",
        "free_quota": "新用户免费 credits",
        "free_models": ["llama-3.1-70b", "llama-3.1-8b", "mistral-7b", "qwen2.5-7b"],
        "capabilities": ["chat", "tool_call"],
        "regions": ["global"],
        "retention_mode": "provider_retained",
        "notes": "Inference.net 开源模型推理平台",
    },
    "lambda": {
        "provider": "lambda",
        "name": "Lambda Labs",
        "base_url": "https://api.lambdalabs.com/v1",
        "protocol": "openai",
        "signup_url": "https://lambdalabs.com/",
        "free_quota": "注册 500 次免费",
        "free_models": ["llama-3.1-405b-instruct", "llama-3.1-70b-instruct", "llama-3.1-8b-instruct"],
        "capabilities": ["chat", "tool_call", "json_mode"],
        "regions": ["global"],
        "retention_mode": "provider_retained",
        "notes": "Lambda Labs 提供 Llama 3.1 系列免费推理 API",
    },
    "fal": {
        "provider": "fal",
        "name": "Fal.ai",
        "base_url": "https://fal.run",
        "protocol": "openai",
        "signup_url": "https://fal.ai/",
        "free_quota": "新用户 $1 试用",
        "free_models": ["fal-ai/llama-3.1-8b-instruct", "fal-ai/llama-3.1-70b-instruct", "fal-ai/qwen-2.5-72b"],
        "capabilities": ["chat", "vision"],
        "regions": ["global"],
        "retention_mode": "provider_retained",
        "notes": "Fal.ai 高速推理平台，新用户 $1 试用",
    },
    "bentocloud": {
        "provider": "bentocloud",
        "name": "BentoML BentoCloud",
        "base_url": "https://api.bentocloud.com/v1",
        "protocol": "openai",
        "signup_url": "https://bentocloud.com/",
        "free_quota": "新用户 $20 试用",
        "free_models": ["llama-3.1", "qwen", "mistral"],
        "capabilities": ["chat"],
        "regions": ["global"],
        "retention_mode": "provider_retained",
        "notes": "BentoML BentoCloud 模型部署平台，新用户 $20 试用",
    },
    "xai": {
        "provider": "xai",
        "name": "xAI Grok",
        "base_url": "https://api.x.ai/v1",
        "protocol": "openai",
        "signup_url": "https://x.ai/",
        "free_quota": "每月 $25 免费额度",
        "free_models": ["grok-2", "grok-2-vision", "grok-beta", "grok-vision-beta", "grok-2-1212"],
        "capabilities": ["chat", "vision", "tool_call", "reasoning"],
        "regions": ["global"],
        "retention_mode": "provider_retained",
        "notes": "xAI Grok 模型，每月 $25 免费额度",
    },
    "nvidia": {
        "provider": "nvidia",
        "name": "NVIDIA NIM",
        "base_url": "https://integrate.api.nvidia.com/v1",
        "protocol": "openai",
        "signup_url": "https://build.nvidia.com/",
        "free_quota": "注册 1000 credits",
        "free_models": ["meta/llama-3.1-405b-instruct", "meta/llama-3.1-70b-instruct", "meta/llama-3.1-8b-instruct", "nvidia/llama-3.1-nemotron-70b-instruct", "qwen/qwen2.5-coder-32b-instruct"],
        "capabilities": ["chat", "tool_call", "json_mode", "vision"],
        "regions": ["global"],
        "retention_mode": "provider_retained",
        "notes": "NVIDIA NIM 开源模型推理 API，注册赠送 1000 credits",
    },
    "kluster": {
        "provider": "kluster",
        "name": "Kluster AI",
        "base_url": "https://api.kluster.ai/v1",
        "protocol": "openai",
        "signup_url": "https://kluster.ai/",
        "free_quota": "新用户 $5",
        "free_models": ["meta-llama/Llama-3.3-70B-Instruct", "deepseek-ai/DeepSeek-V3", "deepseek-ai/DeepSeek-R1", "Qwen/Qwen2.5-72B-Instruct"],
        "capabilities": ["chat", "reasoning", "tool_call"],
        "regions": ["global"],
        "retention_mode": "provider_retained",
        "notes": "Kluster AI 开源模型推理，新用户 $5 额度",
    },
    "hyperbolic": {
        "provider": "hyperbolic",
        "name": "Hyperbolic",
        "base_url": "https://api.hyperbolic.xyz/v1",
        "protocol": "openai",
        "signup_url": "https://hyperbolic.xyz/",
        "free_quota": "新用户 $10",
        "free_models": ["meta-llama/Llama-3.1-405B-Instruct", "meta-llama/Meta-Llama-3.1-70B-Instruct", "Qwen/Qwen2.5-72B-Instruct", "deepseek-ai/DeepSeek-V3"],
        "capabilities": ["chat", "reasoning"],
        "regions": ["global"],
        "retention_mode": "provider_retained",
        "notes": "Hyperbolic GPU 推理平台，新用户 $10 额度",
    },
    "ai21": {
        "provider": "ai21",
        "name": "AI21 Labs",
        "base_url": "https://api.ai21.com/v1",
        "protocol": "openai",
        "signup_url": "https://www.ai21.com/",
        "free_quota": "注册 1000 credits",
        "free_models": ["jamba-1.5-mini", "jamba-1.5-large", "jamba-instruct"],
        "capabilities": ["chat", "tool_call", "long_context"],
        "regions": ["global"],
        "retention_mode": "provider_retained",
        "notes": "AI21 Jamba 系列 Mamba 混合架构模型",
    },
    "reka": {
        "provider": "reka",
        "name": "Reka AI",
        "base_url": "https://api.reka.ai/v1",
        "protocol": "openai",
        "signup_url": "https://www.reka.ai/",
        "free_quota": "注册 $5 试用",
        "free_models": ["reka-core", "reka-flash", "reka-flash-3", "reka-edge"],
        "capabilities": ["chat", "vision", "reasoning"],
        "regions": ["global"],
        "retention_mode": "provider_retained",
        "notes": "Reka AI 多模态模型，注册 $5 试用",
    },
    "watsonx": {
        "provider": "watsonx",
        "name": "IBM watsonx",
        "base_url": "https://us-south.ml.cloud.ibm.com/ml/v1",
        "protocol": "openai",
        "signup_url": "https://www.ibm.com/watsonx",
        "free_quota": "IBM Cloud Lite 每月 1000 次",
        "free_models": ["meta-llama/llama-3-1-70b-instruct", "meta-llama/llama-3-405b-instruct", "mistralai/mixtral-8x7b-instruct-v01"],
        "capabilities": ["chat", "tool_call"],
        "regions": ["global"],
        "retention_mode": "provider_retained",
        "notes": "IBM watsonx.ai Lite 套餐每月 1000 次免费调用",
    },
    "lightning": {
        "provider": "lightning",
        "name": "Lightning AI",
        "base_url": "https://lightning.ai/api/v1",
        "protocol": "openai",
        "signup_url": "https://lightning.ai/",
        "free_quota": "每月 $15 免费 GPU",
        "free_models": ["llama-3.1", "qwen2.5", "deepseek"],
        "capabilities": ["chat"],
        "regions": ["global"],
        "retention_mode": "provider_retained",
        "notes": "Lightning AI Studio 每月 $15 免费 GPU 额度，可自部署开源模型",
    },
    "duckduckgo": {
        "provider": "duckduckgo",
        "name": "DuckDuckGo AI Chat",
        "base_url": "https://duckduckgo.com/duckchat/v1",
        "protocol": "openai",
        "signup_url": "https://duckduckgo.com/chat",
        "free_quota": "完全免费无需 API Key",
        "free_models": ["gpt-4o-mini", "claude-3-haiku-20240307", "llama-3.1-70b-instant", "mixtral-8x7b-32768", "o3-mini"],
        "capabilities": ["chat", "reasoning"],
        "regions": ["global"],
        "retention_mode": "provider_retained",
        "notes": "DuckDuckGo AI Chat 完全免费，无需 API Key 即可使用",
    },
    "gpt4free": {
        "provider": "gpt4free",
        "name": "GPT4Free",
        "base_url": "http://localhost:1337/v1",
        "protocol": "openai",
        "signup_url": "https://github.com/xtekky/gpt4free",
        "free_quota": "完全免费（自部署聚合）",
        "free_models": ["gpt-4", "gpt-3.5-turbo", "claude-3-haiku", "llama-3.1-70b", "gemini-1.5-flash"],
        "capabilities": ["chat"],
        "regions": ["self_hosted"],
        "retention_mode": "provider_retained",
        "notes": "GPT4Free 自部署聚合代理多个免费供应商",
    },
    "aihubmix": {
        "provider": "aihubmix",
        "name": "AiHubMix",
        "base_url": "https://api.aihubmix.com/v1",
        "protocol": "openai",
        "signup_url": "https://aihubmix.com/",
        "free_quota": "注册 $1 试用",
        "free_models": ["gpt-4o-mini", "gpt-3.5-turbo", "claude-3-haiku", "gemini-1.5-flash", "deepseek-chat", "qwen-turbo", "glm-4-flash"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode"],
        "regions": ["cn"],
        "retention_mode": "provider_retained",
        "notes": "AiHubMix 聚合多模型 API 平台，注册赠送 $1 试用",
    },
    "api2d": {
        "provider": "api2d",
        "name": "API2D",
        "base_url": "https://oa.api2d.net/v1",
        "protocol": "openai",
        "signup_url": "https://api2d.com/",
        "free_quota": "注册 $1 额度",
        "free_models": ["gpt-3.5-turbo", "gpt-4o-mini", "gpt-4o", "claude-3-haiku", "gemini-1.5-flash"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode"],
        "regions": ["cn"],
        "retention_mode": "provider_retained",
        "notes": "API2D 中转 OpenAI/Claude/Gemini，注册赠送 $1 额度",
    },
    "openai_hk": {
        "provider": "openai_hk",
        "name": "OpenAI-HK",
        "base_url": "https://api.openai-hk.com/v1",
        "protocol": "openai",
        "signup_url": "https://openai-hk.com/",
        "free_quota": "注册 $1 + 每日签到",
        "free_models": ["gpt-4o-mini", "gpt-3.5-turbo", "gpt-4o", "claude-3-haiku", "gemini-1.5-flash", "deepseek-chat"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode"],
        "regions": ["cn"],
        "retention_mode": "provider_retained",
        "notes": "OpenAI-HK 中转聚合平台，注册 $1 + 每日签到送额度",
    },
    "closeai": {
        "provider": "closeai",
        "name": "Closeai",
        "base_url": "https://api.closeai-proxy.xyz/v1",
        "protocol": "openai",
        "signup_url": "https://closeai-proxy.xyz/",
        "free_quota": "注册 $1 试用",
        "free_models": ["gpt-4o-mini", "gpt-4o", "gpt-3.5-turbo", "claude-3-5-sonnet", "claude-3-haiku"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode"],
        "regions": ["cn"],
        "retention_mode": "provider_retained",
        "notes": "Closeai 代理 OpenAI/Claude，注册赠送 $1 试用",
    },
    "zhizengzeng": {
        "provider": "zhizengzeng",
        "name": "智增增",
        "base_url": "https://api.zhizengzheng.com/v1",
        "protocol": "openai",
        "signup_url": "https://zhizengzheng.com/",
        "free_quota": "注册免费额度",
        "free_models": ["gpt-4o-mini", "gpt-4o", "claude-3-haiku", "gemini-1.5-flash", "deepseek-chat", "qwen-turbo", "glm-4-flash"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode"],
        "regions": ["cn"],
        "retention_mode": "provider_retained",
        "notes": "智增增聚合 API 平台，注册赠送免费额度",
    },
    "ohmygpt": {
        "provider": "ohmygpt",
        "name": "OhMyGPT",
        "base_url": "https://api.ohmygpt.com/v1",
        "protocol": "openai",
        "signup_url": "https://www.ohmygpt.com/",
        "free_quota": "注册 $1 试用",
        "free_models": ["gpt-4o-mini", "gpt-4o", "claude-3-haiku", "gemini-1.5-flash", "deepseek-chat"],
        "capabilities": ["chat", "vision", "tool_call"],
        "regions": ["cn"],
        "retention_mode": "provider_retained",
        "notes": "OhMyGPT 聚合 API 中转，注册赠送 $1 试用",
    },
    "chatanywhere": {
        "provider": "chatanywhere",
        "name": "ChatAnywhere",
        "base_url": "https://api.chatanywhere.cn/v1",
        "protocol": "openai",
        "signup_url": "https://chatanywhere.com/",
        "free_quota": "免费 $1-$10（研究/教育）",
        "free_models": ["gpt-3.5-turbo", "gpt-4o-mini", "gpt-4o", "claude-3-haiku"],
        "capabilities": ["chat", "vision", "tool_call"],
        "regions": ["cn"],
        "retention_mode": "provider_retained",
        "notes": "ChatAnywhere 面向研究/教育用户提供 $1-$10 免费额度",
    },
    "ai_ls": {
        "provider": "ai_ls",
        "name": "AI.LS",
        "base_url": "https://api.ai.ls/v1",
        "protocol": "openai",
        "signup_url": "https://api.ai.ls/",
        "free_quota": "注册免费额度",
        "free_models": ["gpt-4o-mini", "gpt-3.5-turbo", "claude-3-haiku", "gemini-1.5-flash", "deepseek-chat"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode"],
        "regions": ["global"],
        "retention_mode": "provider_retained",
        "notes": "AI.LS 聚合代理多模型 API，注册赠送免费额度",
    },
    "v3api": {
        "provider": "v3api",
        "name": "V3 API",
        "base_url": "https://api.v3api.top/v1",
        "protocol": "openai",
        "signup_url": "https://v3api.top/",
        "free_quota": "注册 $1 试用",
        "free_models": ["gpt-4o-mini", "gpt-4o", "claude-3-haiku", "gemini-1.5-flash", "deepseek-chat", "qwen-turbo"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode"],
        "regions": ["cn"],
        "retention_mode": "provider_retained",
        "notes": "V3 API 国内中转聚合平台，注册赠送 $1 试用",
    },
    "gptgod": {
        "provider": "gptgod",
        "name": "GPTGOD",
        "base_url": "https://api.gptgod.net/v1",
        "protocol": "openai",
        "signup_url": "https://gptgod.net/",
        "free_quota": "注册 $1 试用",
        "free_models": ["gpt-4o-mini", "gpt-4o", "claude-3-haiku", "gemini-1.5-flash", "deepseek-chat"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode"],
        "regions": ["cn"],
        "retention_mode": "provider_retained",
        "notes": "GPTGOD 聚合多模型 API 中转，注册赠送 $1 试用",
    },
    "minimax": {
        "provider": "minimax",
        "name": "MiniMax",
        "base_url": "https://api.minimax.chat/v1",
        "protocol": "openai",
        "signup_url": "https://www.minimaxi.com/",
        "free_quota": "新用户免费 tokens",
        "free_models": ["abab6.5s-chat", "abab6.5-chat", "abab6-chat"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode"],
        "regions": ["cn"],
        "retention_mode": "provider_retained",
        "notes": "MiniMax 大模型，新用户赠送免费 token 额度",
    },
    "baichuan": {
        "provider": "baichuan",
        "name": "百川大模型",
        "base_url": "https://api.baichuan-ai.com/v1",
        "protocol": "openai",
        "signup_url": "https://www.baichuan-ai.com/",
        "free_quota": "新用户免费 tokens",
        "free_models": ["Baichuan4-Turbo", "Baichuan3-Turbo", "Baichuan2-Turbo"],
        "capabilities": ["chat", "tool_call", "json_mode"],
        "regions": ["cn"],
        "retention_mode": "provider_retained",
        "notes": "百川大模型 OpenAI 兼容接口，新用户赠送免费 token 额度",
    },
    "metaso": {
        "provider": "metaso",
        "name": "秘塔 AI",
        "base_url": "https://api.metaso.cn/v1",
        "protocol": "openai",
        "signup_url": "https://metaso.cn/",
        "free_quota": "注册免费额度",
        "free_models": ["metaso-gpt", "metaso-search"],
        "capabilities": ["chat", "tool_call"],
        "regions": ["cn"],
        "retention_mode": "provider_retained",
        "notes": "秘塔 AI 搜索 + 大模型 API，注册赠送免费额度",
    },
    "ppio": {
        "provider": "ppio",
        "name": "PPIO 派欧云",
        "base_url": "https://api.ppinfra.com/v2/openai",
        "protocol": "openai",
        "signup_url": "https://ppio.cn/",
        "free_quota": "新用户 $1 试用",
        "free_models": ["deepseek/deepseek-v3", "deepseek/deepseek-r1", "meta/llama-3.1-70b-instruct", "qwen/qwen2.5-72b-instruct"],
        "capabilities": ["chat", "reasoning", "tool_call"],
        "regions": ["cn"],
        "retention_mode": "provider_retained",
        "notes": "PPIO 派欧云计算开源模型推理 API，新用户赠送 $1 试用",
    },
    "ollama": {
        "provider": "ollama",
        "name": "Ollama",
        "base_url": "http://localhost:11434/v1",
        "protocol": "openai",
        "signup_url": "https://ollama.com/",
        "free_quota": "完全免费（本地部署）",
        "free_models": ["llama3.1", "qwen2.5", "deepseek-r1", "mistral", "gemma2"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode"],
        "regions": ["self_hosted"],
        "retention_mode": "provider_retained",
        "notes": "Ollama 本地部署推理框架，完全免费，无需 API Key",
    },
    "oneapi": {
        "provider": "oneapi",
        "name": "One API",
        "base_url": "http://localhost:3000/v1",
        "protocol": "openai",
        "signup_url": "https://github.com/songquanpeng/one-api",
        "free_quota": "完全免费（自部署网关）",
        "free_models": ["gpt-4o-mini", "gpt-3.5-turbo", "claude-3-haiku", "deepseek-chat", "qwen-turbo"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode"],
        "regions": ["self_hosted"],
        "retention_mode": "provider_retained",
        "notes": "One API 自部署 API 网关，聚合多供应商，统一 OpenAI 协议",
    },
    "newapi": {
        "provider": "newapi",
        "name": "New API",
        "base_url": "http://localhost:3000/v1",
        "protocol": "openai",
        "signup_url": "https://github.com/Calcium-Ion/new-api",
        "free_quota": "完全免费（自部署网关）",
        "free_models": ["gpt-4o-mini", "gpt-4o", "claude-3-5-sonnet", "deepseek-chat", "qwen-turbo"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode"],
        "regions": ["self_hosted"],
        "retention_mode": "provider_retained",
        "notes": "New API 自部署 API 网关，One API 增强版，支持更多模型与计费",
    },
    "llamacpp": {
        "provider": "llamacpp",
        "name": "llama.cpp",
        "base_url": "http://localhost:8080/v1",
        "protocol": "openai",
        "signup_url": "https://github.com/ggerganov/llama.cpp",
        "free_quota": "完全免费（自部署）",
        "free_models": ["llama-3.1-8b-instruct", "llama-3.1-70b-instruct", "qwen2.5-7b-instruct", "deepseek-r1"],
        "capabilities": ["chat", "tool_call"],
        "regions": ["self_hosted"],
        "retention_mode": "provider_retained",
        "notes": "llama.cpp 自部署推理框架，OpenAI 兼容 server，完全免费",
    },
    "vllm": {
        "provider": "vllm",
        "name": "vLLM",
        "base_url": "http://localhost:8000/v1",
        "protocol": "openai",
        "signup_url": "https://github.com/vllm-project/vllm",
        "free_quota": "完全免费（自部署）",
        "free_models": ["llama-3.1-70b", "qwen2.5-72b", "deepseek-v3", "mixtral-8x7b"],
        "capabilities": ["chat", "tool_call", "json_mode"],
        "regions": ["self_hosted"],
        "retention_mode": "provider_retained",
        "notes": "vLLM 高性能推理引擎，OpenAI 兼容 API，完全免费",
    },
    "xinference": {
        "provider": "xinference",
        "name": "Xinference",
        "base_url": "http://localhost:9997/v1",
        "protocol": "openai",
        "signup_url": "https://github.com/xorbitsai/inference",
        "free_quota": "完全免费（自部署）",
        "free_models": ["llama-3.1-70b-instruct", "qwen2.5-instruct", "deepseek-v3", "mistral-7b-instruct"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode"],
        "regions": ["self_hosted"],
        "retention_mode": "provider_retained",
        "notes": "Xinference 分布式模型推理平台，OpenAI 兼容 API",
    },
    "localai": {
        "provider": "localai",
        "name": "LocalAI",
        "base_url": "http://localhost:8080/v1",
        "protocol": "openai",
        "signup_url": "https://localai.io/",
        "free_quota": "完全免费（自部署）",
        "free_models": ["gpt-3.5-turbo", "llama-3.1-8b", "qwen2.5-7b", "deepseek-r1"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode", "embedding", "image_generation"],
        "regions": ["self_hosted"],
        "retention_mode": "provider_retained",
        "notes": "LocalAI 自部署 AI 服务，OpenAI 兼容 API，支持文本/图像/嵌入",
    },
    "lmdeploy": {
        "provider": "lmdeploy",
        "name": "LMDeploy",
        "base_url": "http://localhost:23333/v1",
        "protocol": "openai",
        "signup_url": "https://github.com/InternLM/lmdeploy",
        "free_quota": "完全免费（自部署）",
        "free_models": ["internlm2_5-7b-chat", "internlm2_5-20b-chat", "llama-3.1-70b", "qwen2.5-7b"],
        "capabilities": ["chat", "tool_call"],
        "regions": ["self_hosted"],
        "retention_mode": "provider_retained",
        "notes": "LMDeploy 高效推理部署工具，OpenAI 兼容 API",
    },
    "lmstudio": {
        "provider": "lmstudio",
        "name": "LM Studio",
        "base_url": "http://localhost:1234/v1",
        "protocol": "openai",
        "signup_url": "https://lmstudio.ai/",
        "free_quota": "完全免费（本地部署）",
        "free_models": ["llama-3.1-8b-instruct", "qwen2.5-7b-instruct", "deepseek-r1", "mistral-7b-instruct"],
        "capabilities": ["chat", "tool_call", "json_mode"],
        "regions": ["self_hosted"],
        "retention_mode": "provider_retained",
        "notes": "LM Studio 本地模型推理客户端，OpenAI 兼容 API",
    },
    "gpt_link": {
        "provider": "gpt_link",
        "name": "GPTLink",
        "base_url": "https://api.gpt.link/v1",
        "protocol": "openai",
        "signup_url": "https://gpt.link/",
        "free_quota": "注册免费额度",
        "free_models": ["gpt-4o-mini", "gpt-3.5-turbo", "gpt-4o", "claude-3-haiku", "deepseek-chat"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode"],
        "regions": ["cn"],
        "retention_mode": "provider_retained",
        "notes": "GPTLink 聚合 API 中转平台，注册赠送免费额度",
    },
    # ----------------------------------------------------------------------
    # 第四批免费 / 公益供应商（国内中转聚合 / 海外开源 / 自部署网关）
    # ----------------------------------------------------------------------
    "4sapi": {
        "provider": "4sapi",
        "name": "星链 4SAPI 聚合中转",
        "base_url": "https://api.4sapi.com/v1",
        "protocol": "openai",
        "signup_url": "https://4sapi.com/",
        "free_quota": "注册赠送免费额度",
        "free_models": ["gpt-4o-mini", "claude-3-haiku", "gemini-1.5-flash", "deepseek-chat", "glm-4-flash"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode"],
        "regions": ["cn", "global"],
        "retention_mode": "provider_retained",
        "notes": "星链 4SAPI 国内聚合中转平台，OpenAI/Claude/Gemini/国产模型一站调用",
    },
    "147api": {
        "provider": "147api",
        "name": "147API 聚合中转",
        "base_url": "https://api.147api.com/v1",
        "protocol": "openai",
        "signup_url": "https://147api.com/",
        "free_quota": "注册赠送免费额度",
        "free_models": ["gpt-4o-mini", "gpt-4o", "claude-3-haiku", "gemini-1.5-flash", "deepseek-chat"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode"],
        "regions": ["cn", "global"],
        "retention_mode": "provider_retained",
        "notes": "147API 国内中转聚合平台，覆盖主流商业与开源模型",
    },
    "poloapi": {
        "provider": "poloapi",
        "name": "PoloAPI 聚合中转",
        "base_url": "https://api.poloapi.com/v1",
        "protocol": "openai",
        "signup_url": "https://poloapi.com/",
        "free_quota": "注册赠送免费额度",
        "free_models": ["gpt-4o-mini", "claude-3-5-sonnet", "gemini-1.5-flash", "deepseek-chat", "qwen-turbo"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode"],
        "regions": ["cn", "global"],
        "retention_mode": "provider_retained",
        "notes": "PoloAPI 国内中转聚合，主打长文本与高并发场景",
    },
    "aigcbest": {
        "provider": "aigcbest",
        "name": "AIGCBest 聚合",
        "base_url": "https://api.aigcbest.com/v1",
        "protocol": "openai",
        "signup_url": "https://aigcbest.com/",
        "free_quota": "注册赠送免费额度",
        "free_models": ["gpt-4o-mini", "gpt-3.5-turbo", "claude-3-haiku", "gemini-1.5-flash", "deepseek-chat"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode"],
        "regions": ["cn", "global"],
        "retention_mode": "provider_retained",
        "notes": "AIGCBest 多模型聚合 API 平台，待官方确认",
    },
    "deepbricks": {
        "provider": "deepbricks",
        "name": "DeepBricks 推理",
        "base_url": "https://api.deepbricks.ai/v1",
        "protocol": "openai",
        "signup_url": "https://deepbricks.ai/",
        "free_quota": "新用户免费额度",
        "free_models": ["gpt-4o-mini", "claude-3-haiku", "deepseek-chat", "llama-3.1-70b-instruct", "qwen2.5-7b-instruct"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode"],
        "regions": ["global", "us"],
        "retention_mode": "provider_retained",
        "notes": "DeepBricks 商业与开源模型聚合推理平台",
    },
    "vegal": {
        "provider": "vegal",
        "name": "Vegal AI 聚合",
        "base_url": "https://api.v3.ai/v1",
        "protocol": "openai",
        "signup_url": "https://v3.ai/",
        "free_quota": "注册赠送免费额度",
        "free_models": ["gpt-4o-mini", "claude-3-haiku", "gemini-1.5-flash", "deepseek-chat"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode"],
        "regions": ["cn", "global"],
        "retention_mode": "provider_retained",
        "notes": "Vegal AI 多模型聚合中转，待官方确认",
    },
    "siliconflow_global": {
        "provider": "siliconflow_global",
        "name": "硅基流动（海外节点）",
        "base_url": "https://api.siliconflow.com/v1",
        "protocol": "openai",
        "signup_url": "https://cloud.siliconflow.com/",
        "free_quota": "注册送 2000 万 token",
        "free_models": ["deepseek-ai/DeepSeek-V3", "Qwen/Qwen2.5-7B-Instruct", "meta-llama/Meta-Llama-3.1-8B-Instruct"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode", "embedding"],
        "regions": ["global", "us", "sg"],
        "retention_mode": "provider_retained",
        "notes": "硅基流动海外节点，海外直连免备案",
    },
    "openrouter_free": {
        "provider": "openrouter_free",
        "name": "OpenRouter 免费聚合视图",
        "base_url": "https://openrouter.ai/api/v1",
        "protocol": "openai",
        "signup_url": "https://openrouter.ai/",
        "free_quota": "免费模型 RPM 限额",
        "free_models": ["free:qwen-2.5-7b", "free:gemini-2.0-flash", "free:llama-3.3-70b", "free:deepseek-r1", "free:mistral-7b-instruct", "free:phi-3-mini-128k"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode", "reasoning"],
        "regions": ["global", "us", "eu"],
        "retention_mode": "provider_retained",
        "notes": "OpenRouter free: 前缀模型聚合视图，完全免费",
    },
    "poe": {
        "provider": "poe",
        "name": "Poe API",
        "base_url": "https://api.poe.com/v1",
        "protocol": "openai",
        "signup_url": "https://poe.com/",
        "free_quota": "每日免费 compute points",
        "free_models": ["GPT-4o-Mini", "Claude-3-Haiku", "Llama-3.1-70b", "Gemini-1.5-Flash"],
        "capabilities": ["chat", "vision"],
        "regions": ["global", "us"],
        "retention_mode": "provider_retained",
        "notes": "Poe 平台 API，每日赠送 compute points，OpenAI 兼容端点",
    },
    "glm_api_chat": {
        "provider": "glm_api_chat",
        "name": "智谱 chatglm.cn 入口",
        "base_url": "https://chatglm.cn/api/v1",
        "protocol": "openai",
        "signup_url": "https://chatglm.cn/",
        "free_quota": "GLM-4-Flash 免费",
        "free_models": ["glm-4-flash", "glm-4-flashx", "glm-4-air", "glm-4-airx", "glm-4-long"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode", "embedding"],
        "regions": ["cn"],
        "retention_mode": "provider_retained",
        "notes": "智谱 GLM chatglm.cn 入口，glm-4-flash 完全免费",
    },
    "qwenpg": {
        "provider": "qwenpg",
        "name": "通义千问 pg 入口",
        "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "protocol": "openai",
        "signup_url": "https://dashscope.console.aliyun.com/",
        "free_quota": "新用户免费 token",
        "free_models": ["qwen-turbo", "qwen-plus", "qwen-max", "qwen-long", "qwen2.5-7b-instruct"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode", "embedding", "reasoning"],
        "regions": ["cn", "sg"],
        "retention_mode": "provider_retained",
        "notes": "通义千问 DashScope pg 入口，新用户免费额度",
    },
    "fireworks_serverless": {
        "provider": "fireworks_serverless",
        "name": "Fireworks Serverless 推理",
        "base_url": "https://api.fireworks.ai/inference/v1",
        "protocol": "openai",
        "signup_url": "https://fireworks.ai/",
        "free_quota": "新用户免费额度",
        "free_models": ["accounts/fireworks/models/llama-v3p3-70b-instruct", "accounts/fireworks/models/qwen2p5-7b-instruct", "accounts/fireworks/models/llama4-scout-instruct-basic"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode", "reasoning"],
        "regions": ["global", "us"],
        "retention_mode": "provider_retained",
        "notes": "Fireworks AI Serverless 推理，OpenAI 兼容",
    },
    "perplexity_online": {
        "provider": "perplexity_online",
        "name": "Perplexity Online 搜索增强",
        "base_url": "https://api.perplexity.ai",
        "protocol": "openai",
        "signup_url": "https://www.perplexity.ai/",
        "free_quota": "新用户 $5 体验额度",
        "free_models": ["llama-3.1-sonar-small-128k-online", "llama-3.1-sonar-large-128k-online", "llama-3.1-sonar-huge-128k-online"],
        "capabilities": ["chat", "tool_call", "json_mode"],
        "regions": ["global", "us"],
        "retention_mode": "provider_retained",
        "notes": "Perplexity Sonar Online 系列，实时联网搜索增强",
    },
    "openai_forward": {
        "provider": "openai_forward",
        "name": "OpenAI Forward 自部署网关",
        "base_url": "http://localhost:8000/v1",
        "protocol": "openai",
        "signup_url": "https://github.com/KenyonY/openai-forward",
        "free_quota": "完全免费（自部署）",
        "free_models": ["gpt-4o-mini", "gpt-3.5-turbo", "claude-3-haiku", "deepseek-chat", "qwen-turbo"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode"],
        "regions": ["self_hosted"],
        "retention_mode": "provider_retained",
        "notes": "openai-forward 开源 API 网关，自部署聚合多供应商",
    },
    "glhf": {
        "provider": "glhf",
        "name": "glhf.chat 推理",
        "base_url": "https://glhf.chat/api/v1",
        "protocol": "openai",
        "signup_url": "https://glhf.chat/",
        "free_quota": "免费层 RPM 限额",
        "free_models": ["meta-llama/Llama-3.3-70B-Instruct", "meta-llama/Meta-Llama-3.1-8B-Instruct", "Qwen/Qwen2.5-72B-Instruct"],
        "capabilities": ["chat", "tool_call", "json_mode"],
        "regions": ["global", "us"],
        "retention_mode": "provider_retained",
        "notes": "glhf.chat 开源模型免费推理平台",
    },
    "tokenflux": {
        "provider": "tokenflux",
        "name": "TokenFlux 推理",
        "base_url": "https://api.tokenflux.ai/v1",
        "protocol": "openai",
        "signup_url": "https://tokenflux.ai/",
        "free_quota": "新用户免费额度",
        "free_models": ["meta-llama/Llama-3.3-70B-Instruct", "meta-llama/Meta-Llama-3.1-8B-Instruct", "Qwen/Qwen2.5-7B-Instruct"],
        "capabilities": ["chat", "tool_call", "json_mode"],
        "regions": ["global"],
        "retention_mode": "provider_retained",
        "notes": "TokenFlux 开源模型推理平台，待官方确认",
    },
    "llama_api": {
        "provider": "llama_api",
        "name": "Meta Llama API",
        "base_url": "https://api.llama.com/v1",
        "protocol": "openai",
        "signup_url": "https://www.llama.com/",
        "free_quota": "免费层 API 调用",
        "free_models": ["Llama-4-Scout-17B-16E-Instruct", "Llama-4-Maverick-17B-128E-Instruct", "Llama-3.3-70B-Instruct", "Llama-3.1-8B-Instruct"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode", "reasoning"],
        "regions": ["global", "us"],
        "retention_mode": "provider_retained",
        "notes": "Meta 官方 Llama API，OpenAI 兼容协议",
    },
    "openai_compat_proxy": {
        "provider": "openai_compat_proxy",
        "name": "通用 OpenAI 兼容代理",
        "base_url": "https://example.com/v1",
        "protocol": "openai",
        "signup_url": "https://example.com/",
        "free_quota": "由部署方决定",
        "free_models": ["gpt-4o-mini", "gpt-3.5-turbo", "deepseek-chat", "qwen-turbo"],
        "capabilities": ["chat", "vision", "tool_call", "json_mode"],
        "regions": ["self_hosted"],
        "retention_mode": "provider_retained",
        "notes": "通用 OpenAI 兼容代理占位预设，base_url 待官方确认，部署方可自定义",
    },
}


def get_free_preset(provider_key: str) -> dict | None:
    """根据 provider_key 返回免费供应商预设，找不到返回 None。"""
    return FREE_PROVIDER_PRESETS.get(provider_key)


if __name__ == "__main__":
    # 简单完整性检查
    # 历史遗留：少数早期 preset 的 ``provider`` 字段指向 PROVIDER_CATALOG 中的
    # canonical provider（如 gemini_free -> gemini、siliconflow_cn -> siliconflow），
    # 而非 preset key 本身。此处允许这两种合法形态，新增强制要求 provider == key。
    _CANONICAL_PROVIDER_ALIASES = {
        "gemini_free": "gemini",
        "openai_free": "openai",
        "siliconflow_cn": "siliconflow",
    }
    print(f"Total free provider presets: {len(FREE_PROVIDER_PRESETS)}")
    for key, preset in FREE_PROVIDER_PRESETS.items():
        provider = preset.get("provider")
        expected = _CANONICAL_PROVIDER_ALIASES.get(key, key)
        assert provider == expected, f"key mismatch: {key} -> {provider}"
        assert preset.get("base_url"), f"missing base_url: {key}"
        assert preset.get("free_models"), f"missing free_models: {key}"
    print("All presets valid")
