package httpapi

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/workama/workama/apps/gateway/internal/channel"
	"github.com/workama/workama/apps/gateway/internal/relay/adapter"
	_ "github.com/workama/workama/apps/gateway/internal/relay/adapter/openai" // 注册 OpenAI 适配器工厂，供 staging 覆盖渠道解析
	"github.com/workama/workama/apps/gateway/internal/relay/routing"
	"github.com/workama/workama/apps/gateway/internal/server/middleware"
	"github.com/workama/workama/apps/gateway/internal/token"
)

type fakeChannelRepo struct {
	channels []channel.Channel
}

func (f *fakeChannelRepo) ListByModel(ctx context.Context, workspaceID, model string) ([]channel.Channel, error) {
	return f.channels, nil
}

type fakeRouter struct {
	selected *adapter.Channel
}

func (f *fakeRouter) SelectChannel(ctx context.Context, candidates []adapter.Channel, tok *routing.Token) (*adapter.Channel, error) {
	if f.selected != nil {
		return f.selected, nil
	}
	if len(candidates) == 0 {
		return nil, routing.ErrNoChannels
	}
	return &candidates[0], nil
}

func newTestChatHandler(t *testing.T, dbChannels []channel.Channel, upstreamURL string) (*ChatHandler, *httptest.Server) {
	t.Helper()
	repo := &fakeChannelRepo{channels: dbChannels}
	h := NewChat(repo, nil, nil, &fakeRouter{}, nil, slog.New(slog.NewTextHandler(io.Discard, nil)))
	if upstreamURL != "" {
		h.SetStaging(&StagingChannel{
			Provider: "openai",
			BaseURL:  upstreamURL,
			APIKey:   "staging-key",
			Model:    "staging-model",
		})
	}
	return h, nil
}

func chatRequest(t *testing.T, h *ChatHandler, body string) *httptest.ResponseRecorder {
	t.Helper()
	req := httptest.NewRequest(http.MethodPost, "/v1/chat/completions", strings.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	tok := &token.Token{ID: "tok-test", WorkspaceID: "wsp-test", ModelWhitelist: []string{"workama-chat"}}
	req = req.WithContext(context.WithValue(req.Context(), middleware.TokenContextKey, tok))
	rec := httptest.NewRecorder()
	h.ServeHTTP(rec, req)
	return rec
}

func openAIResponse(model, content string) string {
	return fmt.Sprintf(`{"id":"upstream-1","object":"chat.completion","created":1,"model":%q,`+
		`"choices":[{"index":0,"message":{"role":"assistant","content":%q},"finish_reason":"stop"}],`+
		`"usage":{"prompt_tokens":2,"completion_tokens":3,"total_tokens":5}}`, model, content)
}

// TestChatStagingPreference verifies that with LLM_STAGING_* configured the
// staging override channel is tried before DB channels.
func TestChatStagingPreference(t *testing.T) {
	var gotModel string
	upstream := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		var reqBody struct {
			Model string `json:"model"`
		}
		_ = json.NewDecoder(r.Body).Decode(&reqBody)
		gotModel = reqBody.Model
		w.Header().Set("Content-Type", "application/json")
		_, _ = io.WriteString(w, openAIResponse("staging-model", "STAGING-UPSTREAM-REPLY"))
	}))
	defer upstream.Close()

	// DB has a mock channel; if the request ever reached it the reply would
	// contain the local mock text, so a staging reply proves priority.
	h, _ := newTestChatHandler(t, []channel.Channel{{ID: "db-mock", Provider: "mock"}}, upstream.URL)
	rec := chatRequest(t, h, `{"model":"workama-chat","messages":[{"role":"user","content":"hi"}]}`)

	if rec.Code != http.StatusOK {
		t.Fatalf("status = %d, want 200; body=%s", rec.Code, rec.Body.String())
	}
	if !strings.Contains(rec.Body.String(), "STAGING-UPSTREAM-REPLY") {
		t.Fatalf("reply does not come from staging upstream: %s", rec.Body.String())
	}
	if gotModel != "staging-model" {
		t.Fatalf("upstream received model %q, want staging-model", gotModel)
	}
}

// TestChatStagingFallback verifies that when the staging upstream fails the
// request falls back to the DB channel (mirroring server.dispatchChat).
func TestChatStagingFallback(t *testing.T) {
	upstream := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		http.Error(w, "upstream exploded", http.StatusServiceUnavailable)
	}))
	defer upstream.Close()

	h, _ := newTestChatHandler(t, []channel.Channel{{ID: "db-mock", Provider: "mock"}}, upstream.URL)
	rec := chatRequest(t, h, `{"model":"workama-chat","messages":[{"role":"user","content":"hi"}]}`)

	if rec.Code != http.StatusOK {
		t.Fatalf("status = %d, want 200 (DB fallback); body=%s", rec.Code, rec.Body.String())
	}
	if !strings.Contains(rec.Body.String(), "This response is generated by the local verification model") {
		t.Fatalf("expected fallback to DB mock channel, got: %s", rec.Body.String())
	}
}

// TestChatNoStagingKeepsDB verifies the pre-existing behavior when no
// LLM_STAGING_* configuration is present.
func TestChatNoStagingKeepsDB(t *testing.T) {
	h, _ := newTestChatHandler(t, []channel.Channel{{ID: "db-mock", Provider: "mock"}}, "")
	rec := chatRequest(t, h, `{"model":"workama-chat","messages":[{"role":"user","content":"hi"}]}`)

	if rec.Code != http.StatusOK {
		t.Fatalf("status = %d, want 200; body=%s", rec.Code, rec.Body.String())
	}
	if !strings.Contains(rec.Body.String(), "This response is generated by the local verification model") {
		t.Fatalf("expected local mock reply, got: %s", rec.Body.String())
	}
}