package httpapi

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"
)

// mockToolRequest 返回确定性 tool_call（当用户消息以 /native-tool 开头且请求了 tools）。
// 与 server 包旧路径保持相同行为。
func mockToolRequest(body *ChatRequest) map[string]any {
	if len(body.Tools) == 0 {
		return nil
	}
	requested := false
	for _, message := range body.Messages {
		if message.Role == "user" {
			if content, ok := message.Content.(string); ok && strings.HasPrefix(strings.TrimSpace(content), "/native-tool") {
				requested = true
			}
		}
		if requested && message.Role == "tool" {
			return nil
		}
	}
	if !requested {
		return nil
	}
	return map[string]any{"index": 0, "id": "call_mock_native", "type": "function", "function": map[string]any{"name": "file.write", "arguments": "{\"path\":\"native/tool.txt\",\"content\":\"native-tool-ok\"}"}}
}

// mockReply 生成确定性的 mock 回复（本地验证模型语义，与旧路径一致）。
func mockReply(messages []ChatMessage) string {
	last := ""
	contextText := ""
	for _, message := range messages {
		content, ok := message.Content.(string)
		if !ok {
			continue
		}
		if message.Role == "system" && strings.Contains(content, "Attachment context") {
			contextText = content
		}
		if message.Role == "user" {
			last = content
		}
	}
	if strings.TrimSpace(last) == "" {
		return "Please provide a message so I can help."
	}
	if contextText != "" {
		return fmt.Sprintf("I reviewed the attached text and your question. Based on the available context, the key point is: %s", compact(last, 220))
	}
	return fmt.Sprintf("WorkAMA received your request: %s\n\nThis response is generated by the local verification model. Configure an OpenAI-compatible channel to use a production model.", compact(last, 240))
}

func compact(value string, limit int) string {
	value = strings.Join(strings.Fields(value), " ")
	runes := []rune(value)
	if len(runes) <= limit {
		return value
	}
	return string(runes[:limit]) + "..."
}

// streamMock 以 SSE 流式输出 mock 回复（分块 + [DONE]，与 server 包旧路径一致）。
func (h *ChatHandler) streamMock(w http.ResponseWriter, r *http.Request, id, model, reply string) {
	w.Header().Set("Content-Type", "text/event-stream")
	w.Header().Set("Connection", "keep-alive")
	w.Header().Set("X-Accel-Buffering", "no")
	flusher, ok := w.(http.Flusher)
	if !ok {
		writeJSON(w, http.StatusInternalServerError, map[string]any{"error": map[string]any{"code": "E01007", "message": "Streaming is unavailable"}})
		return
	}
	writeSSE(w, map[string]any{
		"id": id, "object": "chat.completion.chunk", "created": time.Now().Unix(), "model": model,
		"choices": []map[string]any{{"index": 0, "delta": map[string]string{"role": "assistant"}, "finish_reason": nil}},
	})
	flusher.Flush()
	for _, chunk := range splitRunes(reply, 12) {
		select {
		case <-r.Context().Done():
			return
		default:
		}
		writeSSE(w, map[string]any{
			"id": id, "object": "chat.completion.chunk", "created": time.Now().Unix(), "model": model,
			"choices": []map[string]any{{"index": 0, "delta": map[string]string{"content": chunk}, "finish_reason": nil}},
		})
		flusher.Flush()
		time.Sleep(12 * time.Millisecond)
	}
	writeSSE(w, map[string]any{
		"id": id, "object": "chat.completion.chunk", "created": time.Now().Unix(), "model": model,
		"choices": []map[string]any{{"index": 0, "delta": map[string]string{}, "finish_reason": "stop"}},
	})
	fmt.Fprint(w, "data: [DONE]\n\n")
	flusher.Flush()
}

// streamMockToolCall 以 SSE 流式输出 mock tool_call。
func (h *ChatHandler) streamMockToolCall(w http.ResponseWriter, id, model string, call map[string]any) {
	w.Header().Set("Content-Type", "text/event-stream")
	w.Header().Set("Connection", "keep-alive")
	w.Header().Set("X-Accel-Buffering", "no")
	flusher, ok := w.(http.Flusher)
	if !ok {
		return
	}
	writeSSE(w, map[string]any{
		"id": id, "object": "chat.completion.chunk", "created": time.Now().Unix(), "model": model,
		"choices": []map[string]any{{"index": 0, "delta": map[string]any{"role": "assistant", "tool_calls": []any{call}}, "finish_reason": nil}},
	})
	flusher.Flush()
	writeSSE(w, map[string]any{
		"id": id, "object": "chat.completion.chunk", "created": time.Now().Unix(), "model": model,
		"choices": []map[string]any{{"index": 0, "delta": map[string]any{}, "finish_reason": "tool_calls"}},
	})
	fmt.Fprint(w, "data: [DONE]\n\n")
	flusher.Flush()
}

// writeSSE 以 SSE 格式写入一行 data。
func writeSSE(w io.Writer, value any) {
	raw, err := json.Marshal(value)
	if err != nil {
		return
	}
	fmt.Fprintf(w, "data: %s\n\n", raw)
}

// splitRunes 把字符串按 rune 切分为不超过 limit 个 rune 的块。
func splitRunes(value string, limit int) []string {
	runes := []rune(value)
	if limit <= 0 {
		limit = 12
	}
	var out []string
	for i := 0; i < len(runes); i += limit {
		end := i + limit
		if end > len(runes) {
			end = len(runes)
		}
		out = append(out, string(runes[i:end]))
	}
	return out
}
