import { useEffect, useState, type ReactNode } from 'react'
import { Link, NavLink, Outlet, useLocation, useNavigate } from 'react-router-dom'
import { Activity, BarChart3, BookOpen, Bot, Boxes, ChevronDown, ChevronRight, CircleHelp, Code2, Command, FileText, Gift, GitBranch, Globe2, KeyRound, LayoutDashboard, LifeBuoy, LogOut, Menu, MessageSquare, Network, PanelLeftClose, PanelLeftOpen, Palette, Receipt, Search, Settings, ShieldCheck, SlidersHorizontal, Sparkles, Users, Workflow, X, Zap } from 'lucide-react'
import { useAuth } from './auth'
import { IconButton } from './ui'
import { useUiStore } from './stores/ui'
import { LocaleToggle, useLocale } from './locale'
import type { MessageKey } from '@workama/i18n'

type NavItem = { to: string; label: string; icon: typeof Activity; admin?: boolean }
const primary: NavItem[] = [{ to: '/chat', label: 'AMA Chat', icon: MessageSquare }, { to: '/knowledge', label: 'Knowledge', icon: BookOpen }, { to: '/workflows', label: 'Workflows', icon: Workflow }, { to: '/ama-design', label: 'AMA Design', icon: Palette }, { to: '/work', label: 'Work plans', icon: GitBranch }, { to: '/agents', label: 'Agents', icon: Bot }, { to: '/agents/automations', label: 'Automations', icon: Zap }]
const platform: NavItem[] = [{ to: '/gateway/channels', label: 'Gateway', icon: Network, admin: true }, { to: '/gateway/usage', label: 'Usage & spend', icon: BarChart3, admin: true }, { to: '/gateway/free-providers', label: 'Free providers', icon: Gift, admin: true }, { to: '/gateway/import-diagnostics', label: 'Import diagnostics', icon: SlidersHorizontal, admin: true }, { to: '/admin/operations', label: 'Operations', icon: Activity, admin: true }, { to: '/admin/audit', label: 'Audit & evidence', icon: FileText, admin: true }, { to: '/admin/members', label: 'Members', icon: Users, admin: true }]
const workspace: NavItem[] = [{ to: '/admin/security', label: 'Security', icon: ShieldCheck }, { to: '/admin/settings', label: 'Workspace settings', icon: Settings }, { to: '/admin/integrations', label: 'Integrations', icon: Boxes }, { to: '/admin/enterprise-identity', label: 'Enterprise identity', icon: ShieldCheck, admin: true }, { to: '/admin/compliance', label: 'Compliance center', icon: ShieldCheck, admin: true }, { to: '/admin/billing', label: 'Billing', icon: Receipt, admin: true }]

const navCopy: Record<string, MessageKey> = {
  'AMA Chat': 'nav.amaChat', Knowledge: 'nav.knowledge', Workflows: 'nav.workflows', 'AMA Design': 'nav.amaDesign', 'Work plans': 'nav.workPlans', Agents: 'nav.agents', Automations: 'nav.automations', Gateway: 'nav.gateway', 'Usage & spend': 'nav.usageSpend', 'Import diagnostics': 'nav.importDiagnostics', Operations: 'nav.operations', 'Audit & evidence': 'nav.auditEvidence', Members: 'nav.members', Security: 'nav.security', 'Workspace settings': 'nav.workspaceSettings', Integrations: 'nav.integrations', 'Enterprise identity': 'nav.enterpriseIdentity', 'Compliance center': 'nav.compliance', Billing: 'nav.billing', Search: 'nav.search', 'Global search': 'nav.search', 'Help center': 'nav.help', 'Free providers': 'nav.freeProviders',
}
const groupCopy: Record<string, MessageKey> = { Operate: 'nav.operate', Platform: 'nav.platform', Workspace: 'nav.workspace', 'Quick access': 'nav.quickAccess' }

function Item({ item, onNavigate }: { item: NavItem; onNavigate: () => void }) { const { t } = useLocale(); const Icon = item.icon; return <NavLink to={item.to} onClick={onNavigate} className={({ isActive }: { isActive: boolean }) => `nav-item ${isActive ? 'active' : ''}`}><Icon size={17} strokeWidth={1.8} /><span>{t(navCopy[item.label] ?? 'nav.search')}</span>{item.admin && <span className="nav-visibility">{t('nav.admin')}</span>}</NavLink> }
function NavGroup({ title, items, isAdmin, onNavigate }: { title: string; items: NavItem[]; isAdmin: boolean; onNavigate: () => void }) { const { t } = useLocale(); return <div className="nav-group"><div className="nav-group-title">{t(groupCopy[title] ?? 'nav.operate')}</div>{items.filter((item) => !item.admin || isAdmin).map((item) => <Item key={item.to} item={item} onNavigate={onNavigate} />)}</div> }

export function ConsoleLayout() {
  const { user, isAdmin, logout } = useAuth(); const { t, locale } = useLocale(); const [mobileOpen, setMobileOpen] = useState(false); const collapsed = useUiStore((state) => state.sidebarCollapsed); const setCollapsed = useUiStore((state) => state.setSidebarCollapsed); const navigate = useNavigate(); const location = useLocation()
  const [commandOpen, setCommandOpen] = useState(false)
  const close = () => setMobileOpen(false)
  useEffect(() => {
    const path = location.pathname
    const segment = path.split('/').filter(Boolean)[0] || 'chat'
    const titleMap: Record<string, string> = { chat: 'AMA Chat', knowledge: 'Knowledge', workflows: 'Workflows', 'ama-design': 'AMA Design', work: 'Work plans', agents: 'Agents', 'agents/code': 'Code', 'agents/tools': 'Tools', 'agents/automations': 'Automations', 'gateway/channels': 'Gateway', 'gateway/usage': 'Usage & spend', 'gateway/free-providers': 'Free providers', 'gateway/import-diagnostics': 'Import diagnostics', 'admin/security': 'Security', 'admin/billing': 'Billing', 'admin/audit': 'Audit & evidence', 'admin/operations': 'Operations', 'admin/members': 'Members', 'admin/settings': 'Workspace settings', 'admin/integrations': 'Integrations', 'admin/enterprise-identity': 'Enterprise identity', 'admin/compliance': 'Compliance center', 'admin/observability': 'Observability', search: 'Global search', help: 'Help center' }
    const segKey = path.split('/').filter(Boolean).slice(0, 2).join('/')
    const label = titleMap[segKey] || titleMap[segment] || 'Console'
    document.title = `WorkAMA — ${label}`
    const desc = `WorkAMA console · ${label} · OpenAI-compatible LLM gateway + multi-tenant AI control plane + AMA-Chat/Work/Code/Design agent family + Web/desktop/mobile/miniapp/CLI/browser extension clients.`
    let meta = document.querySelector('meta[name="description"]') as HTMLMetaElement | null
    if (!meta) { meta = document.createElement('meta'); meta.setAttribute('name', 'description'); document.head.appendChild(meta) }
    meta.setAttribute('content', desc)
  }, [location.pathname])
  return <div className={`console-shell ${collapsed ? 'sidebar-collapsed' : ''}`}>
    <aside id="primary-sidebar" className={`sidebar ${mobileOpen ? 'open' : ''}`} aria-label={t('ui.primaryNavigation')}>
      <div className="brand-row"><Link className="brand" to="/chat" onClick={close}><span className="brand-mark"><Sparkles size={16} /></span><span className="brand-name">WorkAMA</span></Link><LocaleToggle /><IconButton label={t('ui.closeNavigation')} className="mobile-close" onClick={close}><X size={18} /></IconButton></div>
      <button className="workspace-switcher" aria-label={`${t('ui.workspaceSwitcher')} ${user?.display_name ?? t('ui.workspace')} ${user?.role ?? 'member'}`}><span className="workspace-avatar">{(user?.display_name ?? 'W')[0]}</span><span aria-hidden="true"><strong>{user?.display_name ?? t('ui.workspace')}</strong><small>{user?.role ?? 'member'} {t('ui.workspace')}</small></span><ChevronDown size={15} /></button>
      <nav><NavGroup title="Operate" items={primary} isAdmin={isAdmin} onNavigate={close} /><NavGroup title="Platform" items={platform} isAdmin={isAdmin} onNavigate={close} /><NavGroup title="Workspace" items={workspace} isAdmin={isAdmin} onNavigate={close} /><div className="nav-group"><div className="nav-group-title">{t(groupCopy['Quick access'])}</div><Item item={{ to: '/search', label: 'Search', icon: Search }} onNavigate={close} /><Item item={{ to: '/help', label: 'Help center', icon: CircleHelp }} onNavigate={close} /></div></nav>
      <div className="sidebar-footer"><Link to="/settings" className="user-card" onClick={close}><span className="avatar">{(user?.display_name ?? 'W')[0]}</span><span><strong>{user?.display_name ?? t('ui.workspaceUser')}</strong><small>{user?.email ?? t('ui.signedIn')}</small></span><ChevronRight size={14} /></Link><button className="sidebar-action" onClick={() => void logout()}><LogOut size={16} />{t('ui.signOut')}</button></div>
    </aside>
    {mobileOpen && <button className="mobile-scrim" aria-label={t('ui.closeNavigation')} onClick={close} />}
    <main className="console-main"><header className="topbar"><IconButton label={mobileOpen ? t('ui.closeNavigation') : t('ui.openNavigation')} className="mobile-menu" aria-expanded={mobileOpen} aria-controls="primary-sidebar" onClick={() => setMobileOpen((value) => !value)}><Menu size={19} /></IconButton><IconButton label={collapsed ? t('ui.expandSidebar') : t('ui.collapseSidebar')} className="desktop-collapse" onClick={() => setCollapsed((value) => !value)}>{collapsed ? <PanelLeftOpen size={18} /> : <PanelLeftClose size={18} />}</IconButton><button className="command-trigger" aria-label={`${t('ui.commandMenu')} ${t('ui.jumpToView')}`} onClick={() => setCommandOpen(true)}><Command size={15} /><span aria-hidden="true">{t('ui.jumpToView')}</span><kbd aria-hidden="true">⌘ K</kbd></button><div className="topbar-spacer" /><Link className="topbar-link" to="/admin/notifications"><Zap size={16} />{t('ui.activity')}</Link><Link className="topbar-link" to="/help"><LifeBuoy size={16} />{t('ui.support')}</Link><span className="trace-pill" title={`${t('ui.currentView')}: ${location.pathname}`}>{t('ui.live')}</span></header><div className="page-content"><Outlet /></div></main>
    {commandOpen && <CommandPalette close={() => setCommandOpen(false)} navigate={(to) => { navigate(to); setCommandOpen(false) }} />}
  </div>
}

function CommandPalette({ close, navigate }: { close: () => void; navigate: (to: string) => void }) { const { t } = useLocale(); const commands = [...primary, ...platform.filter((item) => item.admin), ...workspace, { to: '/search', label: 'Global search', icon: Search } as NavItem]; return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && close()}><div className="command-palette" role="dialog" aria-modal="true" aria-label={t('ui.commandMenu')}><div className="command-search"><Search size={18} /><input autoFocus placeholder={t('ui.jumpToView')} onKeyDown={(event) => { if (event.key === 'Escape') close() }} /></div><div className="command-list">{commands.map((item) => { const Icon = item.icon; return <button key={item.to} onClick={() => navigate(item.to)}><Icon size={17} /><span>{t(navCopy[item.label] ?? 'nav.search')}</span><ChevronRight size={14} /></button> })}</div></div></div> }
