$ErrorActionPreference = 'Stop'
$values=@{}; Get-Content .env | ForEach-Object { if ($_ -match '^([^#=]+)=(.*)$') { $values[$matches[1]]=$matches[2] } }
$login=Invoke-RestMethod -Method Post -Uri 'http://localhost:20200/api/v1/auth/login' -ContentType 'application/json' -Body (@{email=$values.TEST_ACCOUNT_EMAIL;password=$values.TEST_ACCOUNT_PASSWORD}|ConvertTo-Json)
$headers=@{Authorization="Bearer $($login.access_token)"}; $session=Invoke-RestMethod -Method Post -Uri 'http://localhost:20200/api/v1/sessions' -Headers $headers -ContentType 'application/json' -Body '{"title":"Attachment Q&A validation","model":"workama-chat"}'
$content='Temporary file answer code: WAMA-ATTACH-2026'; $bytes=[Text.Encoding]::UTF8.GetBytes($content); $sha=[Security.Cryptography.SHA256]::Create(); $digest=([BitConverter]::ToString($sha.ComputeHash($bytes))).Replace('-','').ToLower()
$prepare=Invoke-RestMethod -Method Post -Uri "http://localhost:20200/api/v1/sessions/$($session.id)/attachment-uploads" -Headers $headers -ContentType 'application/json' -Body (@{filename='temporary-context.txt';content_type='text/plain';size_bytes=$bytes.Length;content_sha256=$digest}|ConvertTo-Json)
Invoke-RestMethod -Method Put -Uri "http://localhost:20200$($prepare.upload_url)" -ContentType 'application/octet-stream' -Body $bytes | Out-Null
$attachment=Invoke-RestMethod -Method Post -Uri "http://localhost:20200/api/v1/sessions/$($session.id)/attachment-uploads/$($prepare.upload_id)/complete" -Headers $headers -ContentType 'application/json' -Body (@{content_sha256=$digest}|ConvertTo-Json)
$metadata=Invoke-RestMethod -Uri "http://localhost:20200/api/v1/attachments/$($attachment.id)" -Headers $headers
$download=(Invoke-WebRequest -Uri "http://localhost:20200/api/v1/attachments/$($attachment.id)/content" -Headers $headers -UseBasicParsing).Content
if ($metadata.status -ne 'ready' -or $metadata.content_sha256 -ne $digest -or $download -ne $content) { throw 'Attachment metadata or download mismatch' }
$ticket=Invoke-RestMethod -Method Post -Uri "http://localhost:20200/api/v1/sessions/$($session.id)/ws-tickets" -Headers $headers; $ws="ws://localhost:20201/ws/sessions/$($session.id)?ticket=$([uri]::EscapeDataString($ticket.ticket))"; $wsResult=node tools/attachment-ws-smoke.mjs $ws $attachment.id | ConvertFrom-Json
try { Invoke-RestMethod -Method Delete -Uri "http://localhost:20200/api/v1/attachments/$($attachment.id)" -Headers $headers -ContentType 'application/json' -Body '{"reason":"reference protection test"}'; throw 'Referenced attachment deletion was allowed' } catch { if ($_.Exception.Response.StatusCode.value__ -ne 409) { throw } }
$unusedPrepare=Invoke-RestMethod -Method Post -Uri "http://localhost:20200/api/v1/sessions/$($session.id)/attachment-uploads" -Headers $headers -ContentType 'application/json' -Body (@{filename='unused.txt';content_type='text/plain';size_bytes=$bytes.Length}|ConvertTo-Json)
Invoke-RestMethod -Method Put -Uri "http://localhost:20200$($unusedPrepare.upload_url)" -ContentType 'application/octet-stream' -Body $bytes | Out-Null
$unused=Invoke-RestMethod -Method Post -Uri "http://localhost:20200/api/v1/sessions/$($session.id)/attachment-uploads/$($unusedPrepare.upload_id)/complete" -Headers $headers -ContentType 'application/json' -Body '{}'
Invoke-RestMethod -Method Delete -Uri "http://localhost:20200/api/v1/attachments/$($unused.id)" -Headers $headers -ContentType 'application/json' -Body '{"reason":"unused temporary file"}' | Out-Null
try { Invoke-RestMethod -Method Post -Uri "http://localhost:20200/api/v1/sessions/$($session.id)/attachment-uploads" -Headers $headers -ContentType 'application/json' -Body '{"filename":"binary.exe","content_type":"application/octet-stream","size_bytes":1}'; throw 'Unsupported format was accepted' } catch { if ($_.Exception.Response.StatusCode.value__ -ne 415) { throw } }
$expiryPrepare=Invoke-RestMethod -Method Post -Uri "http://localhost:20200/api/v1/sessions/$($session.id)/attachment-uploads" -Headers $headers -ContentType 'application/json' -Body (@{filename='expires.txt';content_type='text/plain';size_bytes=$bytes.Length}|ConvertTo-Json)
Invoke-RestMethod -Method Put -Uri "http://localhost:20200$($expiryPrepare.upload_url)" -ContentType 'application/octet-stream' -Body $bytes | Out-Null
$expiring=Invoke-RestMethod -Method Post -Uri "http://localhost:20200/api/v1/sessions/$($session.id)/attachment-uploads/$($expiryPrepare.upload_id)/complete" -Headers $headers -ContentType 'application/json' -Body '{}'
docker compose --env-file .env -f deploy/compose/docker-compose.yml exec -T postgres psql -v ON_ERROR_STOP=1 -U $values.POSTGRES_USER -d $values.POSTGRES_DB -c "UPDATE ag_attachment SET expires_at=now()-interval '1 hour' WHERE id='$($expiring.id)'" | Out-Null
Invoke-RestMethod -Method Put -Uri 'http://localhost:20200/api/v1/admin/lifecycle-policies/attachment' -Headers $headers -ContentType 'application/json' -Body '{"retention_days":1,"batch_size":100,"status":"enabled","runbook":"Verify legal hold and temporary attachment object deletion."}' | Out-Null
$run=Invoke-RestMethod -Method Post -Uri 'http://localhost:20200/api/v1/admin/lifecycle-runs' -Headers $headers -ContentType 'application/json' -Body '{"resource_type":"attachment","dry_run":false}'; $deadline=(Get-Date).AddSeconds(30); $completed=$null
while((Get-Date)-lt $deadline){$runs=Invoke-RestMethod -Uri 'http://localhost:20200/api/v1/admin/lifecycle-runs' -Headers $headers;$completed=$runs.items|Where-Object id -eq $run.id;if($completed.status -eq 'completed'){break};Start-Sleep -Milliseconds 500}
if($completed.status -ne 'completed' -or $completed.processed_count -lt 1){throw 'Attachment lifecycle purge did not complete'}
try { Invoke-RestMethod -Uri "http://localhost:20200/api/v1/attachments/$($expiring.id)" -Headers $headers; throw 'Expired attachment remained' } catch { if ($_.Exception.Response.StatusCode.value__ -ne 404) { throw } }
$evidence=[ordered]@{timestamp=[DateTimeOffset]::UtcNow.ToString('o');attachment_id=$attachment.id;s3_temporary=$true;sha256_verified=$true;download_verified=$true;ws_reference=$wsResult.reference_observed;answer_bytes=$wsResult.answer_bytes;referenced_delete_blocked=$true;unreferenced_delete=$true;format_rejection=$true;lifecycle_purge=$true;expires_at=$attachment.expires_at}; $evidence|ConvertTo-Json|Set-Content quality/evidence/attachment-qa-smoke.json; $evidence|ConvertTo-Json
